[project]
name = "personal-library-studies"
version = "0.1.0"
description = "あれこれライブラリを試していく"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm[proxy]>=1.81.0",
    "llama-index>=0.14.13"
]
